name: Aaron U. Salmon
markdown: redcarpet
pygments: true
baseurl: /aaronsalmon.com

sass:
    syntax: scss        # scss|sass
    style:  expanded  # nested|expanded|compact|compressed

# Owner/author information
owner:
    name:         Aaron U Salmon
    name_alt:     Aaron Salmon
    name_first:   Aaron
    avatar5:      aaron_salmon_july4th.jpg
    avatar4:      aaron_salmon_obama_hug.jpg
    avatar3:      aaron_salmon_garden_leader_telegram_by_Elizabeth_Jackson.jpg
    avatar2:      aaron_salmon_and_laura.jpg
    avatar1:      aaron_salmon_and_aleister.png
    email:        aaronusalmon@gmail.com
    birthday:     07/20/1975
    tel:          773.336.2872
    email:        aaronusalmon@gmail.com
    email:        aaronusalmon@gmail.com
    email:        aaronusalmon@gmail.com
    twitter:      aaronsalmon
    facebook:     aaronsalmon
    github:       aaronsalmon
    crunchbase:   aaron-salmon
    linkedin:     aaronsalmon
    instagram:    aaronsalmon
    youtube:      aaronusalmon
    foursquare:   aaronsalmon
    pinboard:     aaronsalmon
    dribbble:     aaronsalmon
    lastfm:       AcidArgyle
    googleplus:   116734310243264124449 # For Google Authorship https://plus.google.com/authorship